name: CUDA9.2-NVCC

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: install
      run: |
        wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_9.2.148-1_amd64.deb
        sudo dpkg -i cuda-repo-ubuntu1604_9.2.148-1_amd64.deb
        sudo apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub
        sudo apt-get update
        sudo apt-get -y install cuda
    - name: build
      run: /usr/local/cuda/bin/nvcc -std=c++14 --expt-relaxed-constexpr -I. c10/test/util/cuda_complex_test.cu -o test
    - name: run
      run: ./test
    
